name: Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: arc-runner-set
    container:
      image: bubatzlegal/tpmsfe:cicd
    steps:
      - name: Load secrets from 1Password
        id: op-load-secret
        uses: 1password/load-secrets-action@v2
        with:
            export-env: true
        env:
          OP_CONFIG_DIR: /tmp/op
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          TPMSFE_KEEPASSXC_PASSWORD: op://tpmsfe/KeePassXC/password
          TPMSFE_OP_CONNECT_TOKEN: op://tpmsfe/tpmsfe-test-connect/credential
          TPMSFE_OP_CONNECT_HOST: op://tpmsfe/tpmsfe-test-connect/endpoint
          TPMSFE_OP_SERVICE_ACCOUNT_TOKEN: op://tpmsfe/tpmsfe-test-service-account/credential
          SETUP_BW_USERNAME: op://tpmsfe/Vaultwarden/username
          SETUP_BW_PASSWORD: op://tpmsfe/Vaultwarden/password
          SETUP_BW_SERVER: op://tpmsfe/Vaultwarden/endpoint
          SETUP_S3_ACCESS_KEY_ID: op://tpmsfe/S3-Credentials/username
          SETUP_S3_SECRET_ACCESS_KEY: op://tpmsfe/S3-Credentials/password
          SETUP_S3_ENDPOINT: op://tpmsfe/S3-Credentials/endpoint

      - name: Get Keepass Database
        run:
          mc alias set actions ${{ steps.op-load-secret.outputs.SETUP_S3_ENDPOINT }} ${{ steps.op-load-secret.outputs.SETUP_S3_ACCESS_KEY_ID }} ${{ steps.op-load-secret.outputs.SETUP_S3_SECRET_ACCESS_KEY }}
          mc cp actions/tpmsfe/Passwords.kdbx /kp/Passwords.kdbx

      - name: Create Bitwarden Session
        run: |
          bw config server ${{ steps.op-load-secret.outputs.SETUP_BW_SERVER }}
          echo "TPMSFE_BW_SESSION=$(bw login "${{ steps.op-load-secret.outputs.SETUP_BW_USERNAME }}" "${{ steps.op-load-secret.outputs.SETUP_BW_PASSWORD }}" --raw)" >> $GITHUB_ENV
          bw sync

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Run go (automated) tests
        run: go test ./tests/automatic
